version: '3.4'

# this docker configuation is the run flavor (static)

services:
  nginx:
    image: ${DOCKER_USERNAME}/${DC_PREFIX}-${APP}:${APP_VERSION}
    build:
      context: ${NGINX}
      target: production
      dockerfile: ${NGINX}/Dockerfile
      args:
        app_pkg: ${APP_GROUP}-${APP}
        app_ver: ${APP_VERSION}
    container_name: ${DC_PREFIX}-${APP}
    environment:
      - APP_NAME
      - API_PATH
      - BACKEND_PORT
      - BACKEND_HOST
      - API_USER_LIMIT_RATE
      - API_DOWNLOAD_LIMIT_RATE
      - API_USER_BURST
      - API_USER_SCOPE
      - API_GLOBAL_LIMIT_RATE
      - API_GLOBAL_BURST
    ports:
      - ${PORT}:80
    restart: always

networks:
  default:
    external:
      name: ${DC_NETWORK}


