version: '3.4'

services:
  frontend-build:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP_GROUP}
        app_name: ${APP_GROUP}-${APP}
        app_ver: ${APP_VERSION}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_GIT: ${NPM_GIT}
        NPM_VERBOSE: ${NPM_VERBOSE}
    image: ${DC_PREFIX}-${APP}:${APP_VERSION}
    container_name: ${DC_PREFIX}-${APP}:${APP_VERSION}

