version: '2'

services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on: 
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/matchid.conf
      - ./web-app:/var/www/matchID
    ports:
      - "80:80"


  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        proxy: ${http_proxy}
    image: matchid-front:latest
    container_name: matchid-front
    volumes:
      - ./index.html:/matchid/index.html
      - ./.babelrc:/matchid/.babelrc
      - ./.editorconfig:/matchid/.editorconfig 
      - ./.eslintignore:/matchid/.eslintignore
      - ./.eslintrc.js:/matchid/.eslintrc.js 
      - ./matchIdConfig:/matchid/matchIdConfig/
      - ./config:/matchid/config/
      - ./src:/matchid/src/
      - ./static:/cartav/static
      - ./build:/matchid/build/
    ports:
      - "8080:8080"

  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200






